"""empty message

Revision ID: 2cbfce4a113f
Revises: d7995493310c
Create Date: 2020-12-02 02:07:14.883632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbfce4a113f'
down_revision = 'd7995493310c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_login')
    )
    op.create_table('geolocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.String(length=200), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['geolocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('model_notification')
    op.drop_table('model_user')
    op.drop_table('model_geolocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_geolocation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('radius', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_login', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_password', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_login')
    )
    op.create_table('model_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('notification', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    op.drop_table('geolocation')
    op.drop_table('user')
    # ### end Alembic commands ###
