"""empty message

Revision ID: 90ccb84ba22d
Revises: 4127d36a9651
Create Date: 2021-01-11 00:31:24.142175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ccb84ba22d'
down_revision = '4127d36a9651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash_code')
    # ### end Alembic commands ###
