"""empty message

Revision ID: b462e5b3465f
Revises: c606ccf36ae4
Create Date: 2021-01-13 02:05:41.406904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b462e5b3465f'
down_revision = 'c606ccf36ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_subjection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geolocation_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['geolocation_id'], ['geolocation.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_subjection')
    # ### end Alembic commands ###
