"""empty message

Revision ID: b9017d0f9b55
Revises: b462e5b3465f
Create Date: 2021-02-14 17:47:32.999652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9017d0f9b55'
down_revision = 'b462e5b3465f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notesubjection', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notesubjection', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notesubjection', type_='foreignkey')
    op.drop_column('notesubjection', 'creator_id')
    # ### end Alembic commands ###
